import { Controller, Get, Req, Res, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import archiver from 'archiver';
import { Request, Response } from 'express';
import { AuthGuard } from '../auth/auth.guard';
import { ExportService } from './export.service';

@ApiTags('export')
@ApiBearerAuth()
@Controller()
export class ExportController {
  constructor(private exportService: ExportService) {}

  @UseGuards(AuthGuard)
  @Get('v1/export/data')
  @ApiOperation({
    summary: 'Export all user data',
    description:
      'Downloads a ZIP archive with one CSV per resource: user.csv, accounts.csv, account-groups.csv, transactions.csv, entries.csv, budgets.csv, budget-items.csv. A README.txt explains each file.',
  })
  async exportUserData(@Req() req: Request, @Res() res: Response) {
    try {
      const {
        userCsv,
        accountsCsv,
        transactionsCsv,
        entriesCsv,
        budgetsCsv,
        budgetItemsCsv,
        accountGroupsCsv,
        filename,
      } = await this.exportService.exportUserData(req['context']);

      const archive = archiver('zip', {
        zlib: { level: 9 },
      });

      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.zip"`);

      archive.pipe(res);

      archive.append(userCsv, { name: 'user.csv' });
      archive.append(accountsCsv, { name: 'accounts.csv' });
      archive.append(transactionsCsv, { name: 'transactions.csv' });
      archive.append(entriesCsv, { name: 'entries.csv' });
      archive.append(budgetsCsv, { name: 'budgets.csv' });
      archive.append(budgetItemsCsv, { name: 'budget-items.csv' });
      archive.append(accountGroupsCsv, { name: 'account-groups.csv' });

      const readme = this.generateReadme();
      archive.append(readme, { name: 'README.txt' });

      archive.on('error', (error) => {
        throw error;
      });

      await archive.finalize();
    } catch (error) {
      res.status(500).json({
        message: 'Failed to export data',
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  private generateReadme(): string {
    return `
MYDON DATA EXPORT
=================

Export Date: ${new Date().toISOString()}

CONTENTS
--------
This archive contains your personal data from Mydon in CSV format. Mydon uses a
proper double-entry accounting model: a transaction is a header (transactions.csv)
with two or more entries (entries.csv) that balance on baseAmount.

Files included:
- user.csv            : your user profile
- accounts.csv        : all accounts in your ledger
- account-groups.csv  : optional account groupings (SKR-style chart of accounts)
- transactions.csv    : transaction headers (date / description / posted state)
- entries.csv         : the individual debit / credit legs of each transaction
- budgets.csv         : budget plans
- budget-items.csv    : line items within each budget

FILE DESCRIPTIONS
-----------------

user.csv
  - User ID, Name, Email

accounts.csv
  Per account:
  - ID, Code, Name
  - Type (ASSETS, LIABILITIES, EQUITY, INCOME, EXPENSE)
  - Currency
  - Retirement Account flag
  - Active From / Active Until (activity window; empty = open-ended)

  Account balances are not stored — they are derived by summing the corresponding
  entries (DEBIT − CREDIT for ASSETS/EXPENSE; CREDIT − DEBIT otherwise).

account-groups.csv
  Per group:
  - ID, Name, Code

transactions.csv
  Per transaction:
  - ID
  - Date (booking date)
  - Description, Reference
  - Posted At (empty = draft and editable; set = posted and immutable)
  - Reverses Transaction ID (set on reversing transactions)
  - Created At / Updated At

entries.csv
  Per entry (≥2 per transaction):
  - ID, Transaction ID, Account ID
  - Direction (DEBIT or CREDIT)
  - Amount (in entry currency)
  - Currency, FX Rate
  - Base Amount (in the ledger's base currency)
  - AI Suggested flag (true when the account was auto-suggested during import)

budgets.csv
  - ID, Name, Year

budget-items.csv
  Per item: ID, Budget ID/Name, Account ID/Name, Account Group ID/Name,
  Amount, Frequency (monthly | yearly).

---
Generated by Mydon Export Service
`.trim();
  }
}
