import { Controller, Get, Req, Res, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import archiver from 'archiver';
import { Request, Response } from 'express';
import { AuthGuard } from '../auth/auth.guard';
import { ExportService } from './export.service';

@ApiTags('export')
@ApiBearerAuth()
@Controller()
export class ExportController {
  constructor(private exportService: ExportService) {}

  @UseGuards(AuthGuard)
  @Get('v1/export/data')
  @ApiOperation({
    summary: 'Export all user data',
    description: 'Downloads a ZIP file containing all user data (user.csv, accounts.csv, transactions.csv)',
  })
  async exportUserData(@Req() req: Request, @Res() res: Response) {
    try {
      const { userCsv, accountsCsv, transactionsCsv, filename } = await this.exportService.exportUserData(
        req['context'],
      );

      const archive = archiver('zip', {
        zlib: { level: 9 }, // Maximum compression
      });

      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.zip"`);

      archive.pipe(res);

      archive.append(userCsv, { name: 'user.csv' });
      archive.append(accountsCsv, { name: 'accounts.csv' });
      archive.append(transactionsCsv, { name: 'transactions.csv' });

      const readme = this.generateReadme();
      archive.append(readme, { name: 'README.txt' });

      archive.on('error', (error) => {
        console.error('Error generating export:', error);
        throw error;
      });

      await archive.finalize();
    } catch (error) {
      console.error('Export error:', error);
      res.status(500).json({
        message: 'Failed to export data',
        error: error.message,
      });
    }
  }

  private generateReadme(): string {
    return `
MYDON DATA EXPORT
=================

Export Date: ${new Date().toISOString()}

CONTENTS
--------
This archive contains all your personal data from Mydon in CSV format.

Files included:
- user.csv: Your user profile information
- accounts.csv: All your financial accounts
- transactions.csv: All your transactions

FILE DESCRIPTIONS
-----------------

user.csv
  Contains your user profile data including:
  - User ID
  - Name
  - Email address

accounts.csv
  Contains all your financial accounts including:
  - Account ID
  - Account name
  - Account type (ASSETS, LIABILITIES, INCOME, EXPENSE, EQUITY)
  - Currency
  - Current balance
  - Opening balance
  - Retirement account flag

transactions.csv
  Contains all your financial transactions including:
  - Transaction ID
  - Transaction date
  - Description
  - Credit and debit amounts
  - Associated account IDs and names
  - Draft status
  - AI suggestion flags (if applicable)
  - Matched transaction ID (for AI suggestions)
  - Creation and update timestamps

---
Generated by Mydon Export Service
`.trim();
  }
}
