import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  ApplicationConfig,
  inject,
  provideAppInitializer,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  LucideAlertCircle,
  LucideAlertTriangle,
  LucideAlignJustify,
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowLeftRight,
  LucideArrowRight,
  LucideBot,
  LucideBuilding,
  LucideCheck,
  LucideCheckCircle2,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleDollarSign,
  LucideCreditCard,
  LucideDownload,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideFileUp,
  LucideInfo,
  LucideLayoutDashboard,
  LucideLayoutList,
  LucideLogOut,
  LucideMenu,
  LucidePause,
  LucidePencil,
  LucidePlay,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSettings,
  LucideSettings2,
  LucideTag,
  LucideTrash2,
  LucideUpload,
  LucideWallet,
  LucideX,
  provideLucideIcons,
} from '@lucide/angular';
import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';
import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { AppConfigService } from './services/app-config.service';
import { AuthService } from './services/auth.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideTranslateService({ defaultLanguage: 'en' }),
    ...provideTranslateHttpLoader({ prefix: './assets/i18n/', suffix: '.json' }),
    provideAppInitializer(async () => {
      const appConfig = inject(AppConfigService);
      const authService = inject(AuthService);
      await appConfig.load();
      return authService.init();
    }),
    provideLucideIcons(
      LucideAlertCircle,
      LucideAlertTriangle,
      LucideLayoutDashboard,
      LucideWallet,
      LucideCircleDollarSign,
      LucideSettings2,
      LucideFileText,
      LucideSettings,
      LucideLogOut,
      LucideEye,
      LucideEyeOff,
      LucideSearch,
      LucideMenu,
      LucideChevronRight,
      LucideChevronLeft,
      LucideChevronUp,
      LucideChevronDown,
      LucideFileUp,
      LucideCreditCard,
      LucideBuilding,
      LucideUpload,
      LucideBot,
      LucideArrowDown,
      LucideArrowLeftRight,
      LucideArrowRight,
      LucideTrash2,
      LucideDownload,
      LucideArrowLeft,
      LucideRefreshCw,
      LucidePlus,
      LucideCheck,
      LucideCheckCircle2,
      LucideInfo,
      LucideX,
      LucidePencil,
      LucidePause,
      LucidePlay,
      LucideAlignJustify,
      LucideLayoutList,
      LucideTag,
    ),
  ],
};
