name: On-Pull-Request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5
          cache: 'pnpm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}

      - run: pnpm install

      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t build --parallel=3
